### ISSUE TITLE
Too restrictive access permissions for sink file

### ISSUE THREAD

**Issue by aveprev** [bootique/bootique-metrics#37]
Currently all sink files get read/write owner only permissions (600 in numeric). For some environments it's too restrictive. For example in our environment we have an application running under one user and a process thats checks the application's health status under another.

**Comment by andrus** [comment]
Env permissions are controlled by `umask` , so the fact that they are too restrictive is not directly related to Bootique. Having said that, I see no harm in being able to define permissions explicitly, so the PR is applied with some minor tweaks.

**Comment by aveprev** [comment]
It's actually related. `FileReportSink` is implemented with the usage of  `java.nio.file.Files#createTempFile(Path, String, String, FileAttribute[])` under the hood. `createTempFile` accepts file attribute array as the last parameter. When attribute array is omitted it uses a rather restrictive defaults (owner read and owner write to be precise). See [Java Docs](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#createTempFile-java.nio.file.Path-java.lang.String-java.lang.String-java.nio.file.attribute.FileAttribute...-)

**Comment by andrus** [comment]
Perhaps we should fix the "move" step then to ensure "umask" is honored?

**Comment by aveprev** [comment]
Well, it would be better solution. But it breaks compatibility in some rare cases.

**Comment by andrus** [comment]
> it breaks compatibility in some rare cases.
We can treat it as a bug fix :)

**Comment by andrus** [comment]
> Any idea why "move from tmp file" step

To have a robust system for monitoring. Otherwise there's a race condition between a Bootique app writing the file, and monitoring agents reading it.

**Comment by aveprev** [comment]
> To have a robust system for monitoring. Otherwise there's a race condition between a Bootique app writing the file, and monitoring agents reading it. So it has to be atomic.

Right, ok. So, it means temp file creation should be performed without custom permissions so umask could be implied.
